import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, posix, relative, sep } from "node:path";

// Builds single-file executables with the web UI embedded, for running on a
// bare machine with nothing else installed.
//
//   bun run compile                     this machine's platform
//   bun run compile linux-x64 ...       cross-compile the named platforms
//   bun run compile all                 every platform below

const TARGETS = [
  "linux-x64",
  "linux-arm64",
  "darwin-x64",
  "darwin-arm64",
  "windows-x64",
] as const;
type Target = (typeof TARGETS)[number];

const root = join(import.meta.dir, "..");
const clientDir = join(root, "dist/client");
const entry = join(root, "src/entry/compiled.generated.ts");

function filesUnder(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    return statSync(path).isDirectory() ? filesUnder(path) : [path];
  });
}

async function run(command: string[]) {
  const child = Bun.spawn(command, {
    cwd: root,
    stdio: ["inherit", "inherit", "inherit"],
  });
  if ((await child.exited) !== 0)
    throw new Error(`${command.join(" ")} failed`);
}

await run(["bun", "run", "build"]);

// The entry point for the executable imports every UI file as an embedded
// asset. It is generated because the file names carry content hashes.
const files = filesUnder(clientDir);
const imports = files.map((file, index) => {
  const specifier = relative(join(root, "src/entry"), file)
    .split(sep)
    .join(posix.sep);
  return `import asset${index} from ${JSON.stringify(specifier)} with { type: "file" };`;
});
const table = files.map((file, index) => {
  const url = `/${relative(clientDir, file).split(sep).join(posix.sep)}`;
  return `  ${JSON.stringify(url)}: asset${index},`;
});
writeFileSync(
  entry,
  [
    "// Generated by scripts/compile.ts. Do not edit.",
    "// @ts-nocheck: the imports are embedded files, which the typings describe as modules.",
    'import { main } from "./serve.ts";',
    ...imports,
    "",
    "const assets: Record<string, string> = {",
    ...table,
    "};",
    "",
    "await main((path) => (path in assets ? Bun.file(assets[path]!) : null));",
    "",
  ].join("\n"),
);

const requested = process.argv.slice(2);
const targets: (Target | null)[] =
  requested.length === 0
    ? [null]
    : requested.includes("all")
      ? [...TARGETS]
      : requested.map((name) => {
          if (!TARGETS.includes(name as Target)) {
            throw new Error(
              `Unknown target "${name}". Choose from: ${TARGETS.join(", ")}, all`,
            );
          }
          return name as Target;
        });

for (const target of targets) {
  const windows = target
    ? target.startsWith("windows")
    : process.platform === "win32";
  const outfile = join(
    root,
    "dist",
    `clearance${target ? `-${target}` : ""}${windows ? ".exe" : ""}`,
  );
  await run([
    "bun",
    "build",
    "--compile",
    "--minify",
    "--sourcemap",
    ...(target ? [`--target=bun-${target}`] : []),
    entry,
    "--outfile",
    outfile,
  ]);
  console.log(`Built ${relative(root, outfile)}`);
}
